### ISSUE TITLE
[Bug]: 获取图片以后要手动关闭 不能自动发送出去到QQ群

### ISSUE THREAD

**Issue by DragonSauce** [GC-ZF/nonebot_plugin_bfinfo#3]
### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![图片](https://user-images.githubusercontent.com/42651551/226191718-6963dd15-8b89-43eb-ade5-5841fef02b84.png)

### 出现问题的QQ | QQ

3401588550

**Comment by DragonSauce** [comment]
![TAB51ZJCSKD27 }1K%}~0TB](https://user-images.githubusercontent.com/42651551/226191846-7fe09ef0-0da9-4ab7-b311-fdbe59cd37ac.png)
 不能自动发出Q群 只能手动关闭 才能发出

**Comment by GC-ZF** [comment]
https://github.com/GC-ZF/nonebot_plugin_bfinfo/blob/main/nonebot_plugin_bfinfo/__init__.py#L341
将此行删除
